### PR TITLE
Add `chrono` feature

### PR DESCRIPTION
**Pull request by ThatOneShortGuy**
Fix for #77. Implemented as a new feature `chrono` just like pyo3 does.
I didn't know whether to make it a default feature, but it is now following the pattern from `numpy`.

### CODE REVIEW

**Comment by termoshtt** [comment]
Thanks PR!

> I didn't know whether to make it a default feature, but it is now following the pattern from numpy.

No need to introduce a new feature for `chrono` support. This should be similar to `num_complex` case
https://github.com/Jij-Inc/pyo3-stub-gen/blob/main/pyo3-stub-gen/src/stub_type/builtins.rs#L39C1-L40C50
Could you fix not to use feature?

**Comment by ThatOneShortGuy** [comment]
Here, the feature part has been removed.

**Comment by xnerhu** [comment]
when is it gonna be merged?

**Comment by ThatOneShortGuy** [comment]
@termoshtt

**Comment by gsleap** [comment]
Hi, thanks for adding this PR. I'm eagerly awaiting the PR to be approved, as my rust pyo3 project also needs chrono support!

**Comment by ThatOneShortGuy** [comment]
> Hi, thanks for adding this PR. I'm eagerly awaiting the PR to be approved, as my rust pyo3 project also needs chrono support!

@gsleap in the meantime, I use the PR repo
```toml
[dependencies]
pyo3-stub-gen = { branch = "chrono_feature", default-features = false, optional = true, git = "https://github.com/ThatOneShortGuy/pyo3-stub-gen" }
```

**Pull request merged**
